### PR TITLE
docs: improve docs infrastructure

### LINKED ISSUE #37: Eludris Docs v2
This issue governs all progress regarding the move of Eludris' documentation infrastructure to a much better automated one.

- [x] Create `todel_codegen` module
- [x] Create `autodoc` macro
- [x] Handle exporting and storing model & route data.
- [x] Move docs to `/docs` directory.
- [x] Make custom SSG-driven website to handle rendering markdown and display the generated autodoc info.

### PR DESCRIPTION
**Pull request by EnokiUN**
## Description

This PR adds the frontend for the new Eludris Developer Portal which utilises the new auto-documentation features introduced in #51 (and #52)

closes #37

## This is a **Code Change**

- [x] Docs have been updated to reflect these changes if necessary.
- [x] Changes have been tested.

### CODE REVIEW

**Review by ooliver1 — CHANGES_REQUESTED** [review]

File: codegen/src/autodoc/handle_fn.rs [hunk 1]
```diff
@@ -90,29 +91,25 @@ pub fn handle_fn(attr: TokenStream, item: ItemFn) -> Result<(ItemInfo, String),
...
-                        Span::call_site().into(),
-                        format!("Cannot find type of path param{}", name),
-                    )
-                })?,
-                name,
-            });
+            let param_type = params.remove(&name).ok_or_else(|| {
+                Error::new(
+                    Span::call_site().into(),
+                    format!("Cannot find type of query param{}", name),
```
Comment (ooliver1) [inline codegen/src/autodoc/handle_fn.rs:109]:
```suggestion
                    format!("Cannot find type of query param {}", name),
```

File: docs/src/content/changelogs/0.3.md [hunk 2]
```diff
@@ -0,0 +1,43 @@
...
+date: 'Dec 1 22'
+pr: 10
+---
+
+## API Changes
+
+### Oprish API Changes
+
+- Due to rate limits being a per instance configuration thing, a new [`/rate_limits`
+  route](/404) has been added besides the already pre-existing
```
Comment (ooliver1) [inline docs/src/content/changelogs/0.3.md:12]: I'm a bit confused as to what these hyperlinks are for? Are they missing a link to go to?

**Review by ooliver1 — CHANGES_REQUESTED** [review]

File: docs/src/content/changelogs/0.3.md (hunk 2 above)
Comment (EnokiUN) [reply docs/src/content/changelogs/0.3.md:12]: They've been removed as of 0.3.3 (this version)

Comment (ooliver1) [reply docs/src/content/changelogs/0.3.md:12]: The ones below seem to be an attempt at links
```md
The [`get_instance_info`] route now has a rate-limit.
```

Comment (EnokiUN) [reply docs/src/content/changelogs/0.3.md:12]: Oh, docs have a custom plugin that follows what `docs.rs` does- essentially autolinking stuff in the "[`foo`]" format. Think of it like ":class:`bar`" for sphinx but it only covers autodocumented items

Comment (ooliver1) [reply docs/src/content/changelogs/0.3.md:12]: ~~oh, cringe~~ /s

File: todel/src/models/info.rs [hunk 3]
```diff
@@ -3,7 +3,7 @@ use serde::{Deserialize, Serialize};
 
 /// The instance info payload
```
Comment (ooliver1) [inline todel/src/models/info.rs:4]: Should these end with a `.`?

Comment (EnokiUN) [reply todel/src/models/info.rs:4]: Yup, that'll be added along with the rest of the documentation.

File: codegen/src/autodoc/utils.rs [hunk 4]
```diff
@@ -46,18 +46,20 @@ pub fn display_path_segment(segment: &PathSegment) -> Result<String, Error> {
...
+                    )?)?);
+                    Ok(())
                 } else {
-                    return Err(Error::new(
-                        arg.span(),
-                        "Cannot generated docummentation for non-type generics",
-                    ));
+                    Err(Error::new(
+                        a.span(),
+                        "Cannot generated documentation for non-type generics",
```
Comment (Chromosomologist) [inline codegen/src/autodoc/utils.rs:59]: generate*?

File: docs/src/content/changelogs/0.3.2.md [hunk 5]
```diff
@@ -0,0 +1,20 @@
...
+This version addresses some issues related to deploying production-ready instances
+of Eludris by providing pre-built docker images and a simple CLI.
+
+## API changes
+
+- All mentions of `ratelimit` have become `rate_limit`, this should not break anything.
+
+## Hosting Changes
+
+- Pre-built Docker images now exist, long are gone the days of sitting around for
```
Comment (Chromosomologist) [inline docs/src/content/changelogs/0.3.2.md:16]: long gone are the days*?

File: docs/src/content/docs/cli.md [hunk 6]
```diff
@@ -0,0 +1,133 @@
+---
+title: 'The Eludris CLI'
+description: "Everything you'll need to know to be able to use the all-mighty Eludris CLI!"
```
Comment (Chromosomologist) [inline docs/src/content/docs/cli.md:3]: I believe that's called almighty mmlol

File: docs/src/content/docs/cli.md [hunk 7]
```diff
@@ -0,0 +1,133 @@
...
+This is a command group which is meant to help deal with Effis files in the attachments
+bucket.
+
+#### Remove
+
+```sh
+sudo eludris attachments remove <id>
+```
+
+This command will remove an attachment's file from your instance along with it's
```
Comment (Chromosomologist) [inline docs/src/content/docs/cli.md:120]: its*

File: docs/src/content/docs/conf.md [hunk 8]
```diff
@@ -0,0 +1,86 @@
...
+order: 3
+---
+
+There are two layers of configuration for Eludris instances, `.env` which is used
+for mostly deployment logic such as ports, database URIs and such, or `Eludris.toml`
+which is used to actually customise the behaviour of your instance's outward-facing
+APIs like rate limits and whatnot.
+
+The [eludris/eludris](https://github.com/eludris/eludris) meta repository comes with
+examples for both `.env` and `Eludris.toml` in the form of `.env.example` and `ExampleELudris.toml`,
```
Comment (Chromosomologist) [inline docs/src/content/docs/conf.md:13]: ExampleEludris* (lowercase L in eludris)

File: docs/src/content/docs/hosting.md [hunk 9]
```diff
@@ -0,0 +1,107 @@
+---
+title: 'Hosting Your Own Instance'
+description: 'All you need to know to get your own Eludris instance running!'
+order: 1
+---
+
+One of our goals ever since the start is to make hosting Eludris instances as simple
+and as friction free as possible. To that extent Eludris has provided an [`Eludris.toml`](./conf.md)
```
Comment (Chromosomologist) [inline docs/src/content/docs/hosting.md:8]: I'd add a comma after "To that extent"

File: docs/src/content/docs/hosting.md [hunk 10]
```diff
@@ -0,0 +1,107 @@
...
+where you can configure your instance as much as you wish and also official docker
+support to help you get started scoff free.
```
Comment (Chromosomologist) [inline docs/src/content/docs/hosting.md:10]: scot-free*?

File: docs/src/content/docs/hosting.md [hunk 11]
```diff
@@ -0,0 +1,107 @@
...
+
+## Deploying a Production Instance With Docker
+
+We really recommend using [Docker](https://www.docker.com/) for production instances,
+it helps keep all the microservices and the external tools they rely on all in one
+neat group of containers without conflicting with anything else related to the host
+system, and without you having to go around OS-dependent installing C libraries.
```
Comment (Chromosomologist) [inline docs/src/content/docs/hosting.md:17]: installing OS-dependent C libraries*?

File: docs/src/content/docs/hosting.md [hunk 12]
```diff
@@ -0,0 +1,107 @@
...
+
+Deploying a production-ready Eludris instance with docker is only 2 simple steps:
+
+1. Install the [Eludris CLI](/docs/cli)
+   You can find more info about this in the [CLI docs](/docs/cli).
+
+2. Run `eludris deploy`
+   This will take you through the process of setting up your own Eludris instance step-by-step
+   without you having to worry about screwing up anywhere.
```
Comment (Chromosomologist) [inline docs/src/content/docs/hosting.md:26]: _Maybe_ use messing up instead here to be slightly less informal?

File: docs/src/content/docs/hosting.md [hunk 13]
```diff
@@ -0,0 +1,107 @@
...
+   the latest version of both should work.
+
+2. Get the latest version of `eludris/eludris`.
+
+```sh
+git clone https://github.com/eludris/eludris && cd eludris
+```
+
+You may also want update the submodules to use the `next` branch if you're trying
+to run a development instance or test a new feature, for that run this instead:
```
Comment (Chromosomologist) [inline docs/src/content/docs/hosting.md:49]: I don't really like the flow of "for that run this instead".

Maybe something like "<...> test a new feature. To do so, run this instead:" could work?

File: docs/src/content/docs/hosting.md [hunk 14]
```diff
@@ -0,0 +1,107 @@
...
+
+```sh
+git clone https://github.com/eludris/eludris --branch=next && cd eludris
+```
+
+3. Configure the `Eludris.toml` file & `.env`.
+
+`.env` is mostly optional thanks to somewhat sane defaults but you'll need to
+have an `eludris` database for MariaDB and a root user with the password as root,
+you can also just change the database URI from the `DATABASE_URL` environment variable.
```
Comment (Chromosomologist) [inline docs/src/content/docs/hosting.md:59]: This deserves to be more than one sentence.

File: docs/src/content/docs/hosting.md [hunk 15]
```diff
@@ -0,0 +1,107 @@
...
+cargo build
+```
+
+```sh
+cargo run --bin oprish
+cargo run --bin pandemonium
+cargo run --bin effis
+```
+
+You will need to run each of these commands in it's own terminal buffer for.
```
Comment (Chromosomologist) [inline docs/src/content/docs/hosting.md:98]: its*

Also, I feel like this sentence got cut short.

File: docs/src/content/docs/hosting.md [hunk 16]
```diff
@@ -0,0 +1,107 @@
...
+
+Depending on your hardware and whether you're building in release mode, this may
+take a bit :D
```
Comment (Chromosomologist) [inline docs/src/content/docs/hosting.md:101]: Not sure about the smiley face lmao

File: docs/src/content/docs/index.md [hunk 17]
```diff
@@ -0,0 +1,66 @@
...
+To that extent Eludris aims to be as easily accessible by everyone, even if they
+do not understand or care about the unique privacy-related features Eludris offers.
+
+In terms of client Eludris is currently officially providing [Pilfer](https://github.com/eludris/pilfer)
+(a lightweight TUI) and [Pengin](https://github.com/eludris/pengin) (a web-based cross-platform client).
+
+However the intent has always been and still remains to be for people to make their
+own clients, toolings, bots, API wrappers and so on.
+
+As such Eludris has tried to convey said support via multiple things, namely the
```
Comment (Chromosomologist) [inline docs/src/content/docs/index.md:33]: I'd add a comma after "As such".

File: docs/src/content/docs/index.md [hunk 18]
```diff
@@ -0,0 +1,66 @@
...
+[Eludris Community organisation](https://github.com/eludris-community) where people
+can add their own creations and the [Eludris Awesome repository](https://github.com/eludris/awesome),
+in addition to these docs.
+
+For more info you can check out our [Official GitHub organisation](htt[s://github.com/eludris)
+or our [website](https://eludris.pages.dev).
+
+While you're also at it consider joining our [Discord Server](https://discord.gg/amMHHjzwb9)
```
Comment (Chromosomologist) [inline docs/src/content/docs/index.md:41]: I'd change this to "While you're at it, consider joining our <...>".

File: docs/src/content/docs/index.md [hunk 19]
```diff
@@ -0,0 +1,66 @@
...
+since that is currently mainly where we hang out, joke around and work on Eludris
+and Eludris related stuff.
+
+## Reading the Docs
+
+The documentation is straight forward, however here are some additional clarifications
```
Comment (Chromosomologist) [inline docs/src/content/docs/index.md:47]: straightforward*, I believe.

File: docs/src/content/docs/index.md [hunk 20]
```diff
@@ -0,0 +1,66 @@
...
+on some of the points where you can get confused.
+
+### Omittability and Nullability
+
+While reading the docs you might notice the use of the question marks next to field
```
Comment (Chromosomologist) [inline docs/src/content/docs/index.md:52]: I'd add a comma after "While reading the docs".

File: docs/src/content/docs/index.md [hunk 21]
```diff
@@ -0,0 +1,66 @@
...
+
+| Field | Type    |
+| ----- | ------- |
+| Foo?  | Integer |
+| Bar   | String? |
+
+Now, you may be wondering what these question marks are going there, it depends
+on where the question mark is, if the question mark is next to the field name like
+in `Foo?`, then that field is omittable, meaning that it is not guaranteed to exist,
+however in a case where it exists it is **guaranteed** to be an Integer.
```
Comment (Chromosomologist) [inline docs/src/content/docs/index.md:63]: Typo'd "doing" as "going".

This deserves to be split into multiple sentences.

I'd suggest something like

> Now, you may be wondering what these question marks are doing there-- it depends
on where the question mark is. if the question mark is next to the field name -- like
in `Foo?` -- then that field is omittable, meaning that it is not guaranteed to exist.
However, in case it exists, it is **guaranteed** to be an Integer.

File: docs/src/content/docs/index.md [hunk 22]
```diff
@@ -0,0 +1,66 @@
...
+
+On the other hand if the question mark is next to the type like in `String?` it means
+that while the field will always be present, its value can be a `null`.
```
Comment (Chromosomologist) [inline docs/src/content/docs/index.md:66]: I'd change this to "<...> it means that, while the field whill always be present, its value <...>".
(Note the first comma)

File: docs/src/content/extra/detailed.md [hunk 23]
```diff
@@ -0,0 +1,206 @@
+---
+title: 'Eludris Detailed'
+description: 'A detailed rundown and initial spec of how Eludris is to eventually function'
+order: 0
+---
+
+## Overview
+
+The main goal with Eludris to provide a uniquely fresh but not entirely new experience. One where anyone can find (or create) a place focused around their interests while having a couple of fundamental policies that greatly improve users' experience.
```
Comment (Chromosomologist) [inline docs/src/content/extra/detailed.md:9]: I think you forgot an "is" -- "The main goal with Eludris **is** to provide <...>".

File: docs/src/content/extra/detailed.md [hunk 24]
```diff
@@ -0,0 +1,206 @@
...
+
+Post-based communities work like how a Subreddit does with members being able to create different types of posts, vote on them and leave comments.
+
+Both community types have shared features however, like roles, nicknames and so on.
+
+Communities can be either public or private.
+
+Communities can _usually_ (depends on the instance) get manually reviewed by an instance admin to get verified if requested by the community's owner.
+
+Verified communities can claim a namespace, getting their own URL invite and are indexed onto list to be easily discoverable. However, doing so adds more restrictions upon them, such as no End-To-End-Encryption, stricter moderation, and so on.
```
Comment (Chromosomologist) [inline docs/src/content/extra/detailed.md:31]: I think this should be "<...> and are indexed onto **a** list to be <...>".

File: docs/src/content/extra/detailed.md [hunk 25]
```diff
@@ -0,0 +1,206 @@
...
+                                       │
+                                       │
+                        48 bit (6 byte) Unix timestamp.
+```
+
+T: 48 bits of the current Unix timestamp (also with the Eludris) epoch.
+
+### KeyDB
+
+Eludris uses a non persistent KeyDB instance to store data that should be fetched with low latency, and is ephemeral such as rate-limit info.
```
Comment (Chromosomologist) [inline docs/src/content/extra/detailed.md:94]: I'd change this to "<...> to store data that should be fetched with low latency and is ephemeral, such as rate-limit info."
(Note, I moved the comma)

File: docs/src/pages/changelogs/[...slug].astro [hunk 26]
```diff
@@ -0,0 +1,35 @@
...
+  <Content />
+  <div style="display: flex; justify-content: center;">
+    <table style="width: auto;">
+      <thead>
+        <th style="border-bottom-left-radius: 5px; border-bottom-width: 2px;">Update PR</th>
+        <th style="border-bottom-right-radius: 5px; border-bottom-width: 2px;"
+          ><a href={`https://github.com/eludris/eludris/pull/${entry.data.pr}`}
+            >eludris#{entry.data.pr}</a
+          ></th
+        >
```
Comment (Chromosomologist) [inline docs/src/pages/changelogs/[...slug].astro:31]: Genuine question-- what the heck is going on with the tag closing here?

**Review by Chromosomologist — CHANGES_REQUESTED** [review]
I am the review that is approaching.

File: docs/src/content/docs/hosting.md (hunk 16 above)
Comment (EnokiUN) [reply docs/src/content/docs/hosting.md:101]: compiling will take anywhere from 2 minutes to 90 years, this serves as a warning to any who shall dare manually compile it

File: docs/src/pages/changelogs/[...slug].astro (hunk 26 above)
Comment (EnokiUN) [reply docs/src/pages/changelogs/[...slug].astro:31]: Prettier

File: docs/src/components/Header.astro [hunk 27]
```diff
@@ -0,0 +1,334 @@
...
+</script>
+
+<script>
+  const slot = document.getElementById('slot-wrapper');
+  const header = document.getElementById('header');
+  const search = document.getElementById('search');
+  const searchBar = document.getElementById('search-bar');
+  const searchInput = document.getElementById('search-input') as HTMLInputElement;
+  const searchStats = document.getElementById('search-stats');
+  const searchResults = document.getElementById('search-results');
```
Comment (teaishealthy) [inline docs/src/components/Header.astro:80]:
```suggestion
  const slot = document.getElementById('slot-wrapper')!;
  const header = document.getElementById('header')!;
  const search = document.getElementById('search')!;
  const searchBar = document.getElementById('search-bar')!;
  const searchInput = document.getElementById('search-input') as HTMLInputElement;
  const searchStats = document.getElementById('search-stats')!;
  const searchResults = document.getElementById('search-results')!;
```

Then you don't need to repeat the null/undefined assertion every time

File: docs/src/components/Header.astro [hunk 28]
```diff
@@ -0,0 +1,334 @@
...
+            (s) =>
+              s.content.toLowerCase().includes(searchInput.value.toLowerCase()) ||
+              s.text.toLowerCase().includes(searchInput.value.toLowerCase())
+          )
+          .map((s) => {
+            let anchor = document.createElement('a');
+            anchor.classList.add('search-result');
+            anchor.href = s.route;
+            let header = document.createElement('h3');
+            header.innerHTML = s.text.replace(
```
Comment (teaishealthy) [inline docs/src/components/Header.astro:161]: xss moment :trollface: /j

File: docs/src/components/Sidebar.astro [hunk 29]
```diff
@@ -0,0 +1,265 @@
...
+  <h3>The Eludris Developer Portal</h3>
+  <ul id="index">
+    <li>
+      <ul id="top-level-pages">
+        {
+          docPages.map((entry) => (
+            <li class="page">
+              <a
+                href={entry.data.order == 0 ? '/' : `/docs/${entry.slug}`}
+                class={slug == entry.slug ? 'active' : ''}
```
Comment (teaishealthy) [inline docs/src/components/Sidebar.astro:57]:
```suggestion
                href={entry.data.order === 0 ? '/' : `/docs/${entry.slug}`}
                class={slug === entry.slug ? 'active' : ''}
```

File: docs/src/components/Header.astro [hunk 30]
```diff
@@ -0,0 +1,334 @@
...
+  <div id="search-results"></div>
+</div>
+
+<script is:inline>
+  const sidebar = document.getElementById('sidebar');
+  const content = document.getElementById('content');
+
+  let theme =
+    localStorage.getItem('theme') ??
+    (window.matchMedia && window.matchMedia('(prefers-color-scheme: dark)').matches
```
Comment (teaishealthy) [inline docs/src/components/Header.astro:32]:
```suggestion
    (window.matchMedia.?('(prefers-color-scheme: dark)').matches
```

**Review by teaishealthy — CHANGES_REQUESTED** [review]

File: docs/src/components/Header.astro (hunk 30 above)
Comment (ooliver1) [reply docs/src/components/Header.astro:32]: I thought the optional chaining operator was `?.`, not `.?`

Comment (teaishealthy) [reply docs/src/components/Header.astro:32]: ^oops typo

**Comment by EnokiUN** [comment]
> https://stackoverflow.com/a/359509

That doesn't carry over to TS tho, no?

File: docs/src/components/Header.astro (hunk 28 above)
Comment (EnokiUN) [reply docs/src/components/Header.astro:161]: > xss moment :trollface: /j

I think we'd have bigger issues if XSS got onto a docs page

**Review by Chromosomologist — APPROVED** [review]
Haha yes.
